services:
  db:
    image: mysql:8
    container_name: corre-83-api
    restart: always
    command: --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: correria83_db
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
