services:
  db:
    image: mysql:8 # Ou postgres:15
    container_name: corre-83-api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: corre83
    ports:
      - "3306:3306"

  adminer: # Opcional: Interface visual para ver o banco no navegador
    image: adminer
    restart: always
    ports:
      - "8080:8080"